---
- name: Convert certificate and key to PKCS12 (optional password)
  hosts: localhost
  gather_facts: no

  vars:
    username: devuser2
    cert_dir: /tmp/certs
    pfx_file: "{{ cert_dir }}/{{ username}}.p12"

    # Leave empty ("") or comment out to make password optional
    # pkcs12_password: "StrongPassword123"
    pkcs12_password: "bigip123"

  tasks:

    - name: Ensure output directory exists
      ansible.builtin.file:
        path: "{{ cert_dir }}"
        state: directory

    - name: Create PKCS12 file from certificate and key (password optional)
      community.crypto.openssl_pkcs12:
        action: export
        path: "{{ pfx_file }}"
        privatekey_path: "{{ cert_dir }}/{{ username}}.key"
        certificate_path: "{{ cert_dir }}/{{ username}}.crt"
        friendly_name: "{{ username}}"
        passphrase: "{{ pkcs12_password | default(omit) }}"
