---
- name: Convert certificate and key to PKCS12 (optional password)
  hosts: localhost
  gather_facts: no
  vars:
    usernames:
      - devuser1
      - devuser2
    cert_dir: user-certs
    # Leave empty ("") or comment out to make password optional
    pkcs12_password: "bigip123"
  tasks:
    - name: Ensure output directory exists
      ansible.builtin.file:
        path: "{{ cert_dir }}"
        state: directory

    - name: Create PKCS12 file from certificate and key (password optional)
      community.crypto.openssl_pkcs12:
        action: export
        path: "{{ cert_dir }}/{{ item }}.p12"
        privatekey_path: "{{ cert_dir }}/{{ item }}.key"
        certificate_path: "{{ cert_dir }}/{{ item }}.crt"
        friendly_name: "{{ item }}"
        passphrase: "{{ pkcs12_password | default(omit) }}"
      loop: "{{ usernames }}"
