- name: Create CSRs with UPN using OpenSSL
  hosts: localhost
  gather_facts: no

  vars:
    domain: TEST.LOCAL
    cert_dir: user-certs
    users:
      - devuser1
      - devuser2

  tasks:
    - name: Ensure cert directory exists
      ansible.builtin.file:
        path: "{{ cert_dir }}"
        state: directory

    - name: Create private keys
      community.crypto.openssl_privatekey:
        path: "{{ cert_dir }}/{{ item }}.key"
        size: 2048
      loop: "{{ users }}"

    - name: Create CSRs with UPN SAN
      community.crypto.openssl_csr:
        path: "{{ cert_dir }}/{{ item }}.csr"
        privatekey_path: "{{ cert_dir }}/{{ item }}.key"
        common_name: "{{ item }}"
        subject_alt_name:
          - "email:{{ item | lower }}@{{ domain | lower }}"
          - "otherName:1.3.6.1.4.1.311.20.2.3;UTF8:{{ item }}@{{ domain }}"
        extended_key_usage:
          - clientAuth
          - "1.3.6.1.4.1.311.10.3.4.1"
      loop: "{{ users }}"
